#database
spring.datasource.url=jdbc:postgresql://localhost:5432/ms_costumer?createDatabaseIfNotExist=true
spring.datasource.username=app
spring.datasource.password=appsecret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=ms_customer
spring.jpa.show-sql=true

#Loggin
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#Kafka
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.consumer.group-id=ms-customers
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.listener.ack-mode=manual